### PR TITLE
Adding German language and ability for additional translations

### PR DESCRIPTION
**Pull request by DFranzen**
I have refactored the speech and text responses for Alexa, to have all the snippets in an external file. This way it was easy to add German responses and other languages should be straight forward in the future.
The used language can be selected in the settings file
The result should feel identical for the English Version, while a new German version of the interaction is present.

I have also implemented the missing SetVolumeIntent, which was in the schema and utterances but missing in code.

### CODE REVIEW

**Comment by DFranzen** [comment]
Sorry for the multiple pull requests, I could not figure out how to invoke travis without resubmitting.

**Comment by declension** [comment]
Hi @DFranzen. Thank you for the PR, some great ideas there!

Generally it's better if you raise an issue first to allow discussion around direction. I could help out with creating them if you want.  It seems like there are two (or three) logical changes here: 
 * Internationalising
 * German translation based on this
* `SetVolumeIntent` support.

If you could split the smaller one(s) out (i.e. a separate PR from `master`), it would make merging easier as they can usually go in (first) without much fuss. 

For the internationalisation, this could be using a [Python internationalisation framework](https://docs.python.org/3/library/i18n.html). They're a bit clunky sometimes but `gettext` (we use it on [Quod Libet](https://github.com/quodlibet/quodlibet) for the 30+ languages we support and it works well enough. It also solves problems that aren't solved easily - e.g. [plural forms](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).

Ideally there should be some new unit tests around any new code - `squeeze-alexa` is a [highly tested codebase](https://coveralls.io/github/declension/squeeze-alexa) as I'm a big believer in unit / integration testing.

**Comment by DFranzen** [comment]
Alright. Fair enough. I will start a discussion in two separate issues for the SetVolumeIntent and the Internationalisation.

**Comment by DFranzen** [comment]
BTW: I did not mention it directly, but I have the skill up and running on a Raspberry pi

**Comment by declension** [comment]
> Should I/you close this pull request until we reach a verdict?

OK yes - let's shut this one for now

**Pull request closed without merging**
