### PR TITLE
added new version of intent to that works with  intent v1 model 

### LINKED ISSUE #23: Update intents JSON file to new schema
They've only gone and changed it. Looks more like this now:
```javascript
{
  "languageModel": {
    "intents": [
      {
        "name": "AMAZON.CancelIntent",
        "samples": []
      },
      {
        "name": "AMAZON.HelpIntent",
        "samples": []
      },
      {
        "name": "AMAZON.PauseIntent",
        "samples": []
      },
      {
        "name": "AMAZON.ResumeIntent",
        "samples": []
      },
      {
        "name": "AMAZON.StopIntent",
        "samples": []
      }
    ],
    "invocationName": "squeezebox"
  }
}
```

There's an [API for this](https://developer.amazon.com/docs/smapi/interaction-model-operations.html#update-interaction-model) it seems, or the Beta Intents editor claims to do some updating manually (but not sure it works, sigh).

### PR DESCRIPTION
**Pull request by NadirJ**
fixed #23 

Based on some quick tests it looks like this new intent v1 json is working.
(using US English)

Note:
* all slots and values are part of t intent_v1.json
i.e geners, players, and playlists are in intent_v1.json
* uttererances are in intent_v1.json also

I'm not sure how this will work with the german

### CODE REVIEW

**Comment by dougadams** [comment]
Alexa and Lambda noob.

Working on implementing squeeze-alexa.

Thanks for this file. I wasn't sure how to structure the json and txt files in the HowTo with the current skill builder. A great help.

It wouldn't save as is though. Error message that the type "PLAYLIST" was missing synonyms. I deleted the blanks

in the Playlist type:
            {"name": {"value": ""}},

and was able to save.

Now on to the next step.

**Comment by dougadams** [comment]
I also couldn't complete the build with the custom samples in the AMAZON.ShuffleOffintent". Build failed. When I deleted the samples for that intent the build was successful.

**Comment by NadirJ** [comment]
Sorry about the empty playlists values...I used a quick regex and didn't check my work (I'm using my own playlist values). I also fixed up the ShuffleOffIntent

**Comment by declension** [comment]
Thanks @NadirJ 
Been very busy but I plan to get some time to look at all this (plus how this will work internationalised)

**Comment by declension** [comment]
@NadirJ I've updated master a whole bunch to (hopefully) sort out i18n in a better way that will support `v0` *and* `v1` interaction schemas depending on user choice / translation progress.

Now looks like this:
```
metadata
└── intents
    └── v0
        └── locale
            ├── de_DE
            └── en_GB
                └── slots
```

Do you think you could update this PR to move your new file into a `v1/en_US` directory (or `en_GB`, hard to say which it really is)?

Ideally mention this new setup in the [HOWTO section](https://github.com/declension/squeeze-alexa/blob/master/docs/HOWTO.md#update-the-interaction-model) too, but I can do that after merge if you prefer.

**Comment by NadirJ** [comment]
I'll take care of updating the PR. I've only test en_US so it makes sense to put it in v1/locale/en_US

**Comment by declension** [comment]
Thanks @NadirJ :+1: :+1: :+1:

**Pull request merged**
