### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by chatainsim**
Add french translation

### CODE REVIEW

**Comment by declension** [comment]
Thanks @chatainsim - this is great. Something's gone a bit wrong with the translation process though - there's no English (all the `msgid`s should have English and `msgstr` French), so nothing will be registered.

If you look at [the German translation](https://github.com/declension/squeeze-alexa/blob/master/locale/de_DE/LC_MESSAGES/squeeze-alexa.po) it should be clearer what's necessary, or you can use something like [Poedit](https://poedit.net/).

Note that we're soon supporting [Intents v2](https://developer.amazon.com/docs/smapi/smapi-migration.html#changelogv1) (see #23, and #61) which will support translations for slots like the genres, playlists, player names etc.

**Comment by declension** [comment]
Great, looks perfect (but haven't tried it yet - have you tested it with your own skill?). At some point I'll add some automated tests for _new_ (and existing) translations to catch these types of things at PR time.

(Oh and sorry I got the wrong link, I meant intents `v1`... I always forget - they started at `v0` :smile: )

**Comment by declension** [comment]
Thanks @chatainsim !

**Comment by declension** [comment]
Note that this only means _output_ from squeeze-alexa is in French. The utterances still need translating to support _speaking_ to squeeze-alexa in French - that's what `utterances.txt` is for (see [German example](https://github.com/declension/squeeze-alexa/blob/master/metadata/intents/v0/locale/de_DE/utterances.txt)) or the new v1 intent schema is for.

I'll update the CONTRIBUTING as it still doesn't mention all this...

**Comment by chatainsim** [comment]
I haven't tested it yet.
I think I'll translate the utterences first.

**Comment by declension** [comment]
Great. It's working fine - I added a test in 53860cdd that probes the French translation and it's coming out correctly :+1:

**Comment by chatainsim** [comment]
Nice, thanks

**Pull request merged**
